language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - build-tools-30.0.0
    - android-30
    - extra-android-m2repository
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
    - chmod +x gradlew