language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - build-tools-30.0.0
    - android-30
before_install:
    - chmod +x gradlew
    - yes | sdkmanager "platforms;android-30"